[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rosam"
version = "0.1.0"
description = "A package for identifying dynamic systems with local LLM tools"
authors = [{ name = "Hossein Moghimian" }]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]